<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="author" content="<?= config('meta.author') ?>">
		<meta name="keywords" content="<?= config('meta.keywords') ?>">
		<meta name="description" content="<?= config('meta.description') ?>">
		<title><?= $title ?? config('meta.title') ?></title>
		<?= asset('main.css') ?>
		<?= asset('responsive.css') ?>
	</head>
	<body>
